databases:
  - name: employee_server
    databaseName: employee_server
    user: giver

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: employee_server
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50
